exclude:     [nbproject]

author :
  name : Andrey Marushkevych
  email : marushkevych@gmail.com
  github : marushkevych
  twitter : marushkevych
  linkedin : andrey-marushkevych
  google_plus : marushkevych
  stack_exchange: 454839