exclude:     [nbproject]

markdown: redcarpet

permalink: /:year/:month/:day/:title.html

author :
  name : Andrey Marushkevych
  email : marushkevych@gmail.com
  github : marushkevych
  twitter : marushkevych
  linkedin : andrey-marushkevych/7/100/960
  google_plus : AndreyMarushkevych
  stack_exchange: 454839